/**  HomeMade by shoe[box]   Redistribution and use in source and binary forms, with or without   modification, are permitted provided that the following conditions are  met:  * Redistributions of source code must retain the above copyright notice,     this list of conditions and the following disclaimer.    * Redistributions in binary form must reproduce the above copyright    notice, this list of conditions and the following disclaimer in the     documentation and/or other materials provided with the distribution.    * Neither the name of shoe[box] nor the names of its     contributors may be used to endorse or promote products derived from     this software without specific prior written permission.  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS  IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,  THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR  PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR   CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,  EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR  PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF  LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING  NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.*/package org.shoebox.biskwy.commands.actor {	import org.shoebox.biskwy.items.PropsPanelItem;
	import org.shoebox.biskwy.items.PropsPanel;
	import org.shoebox.biskwy.items.ActorProps;
	import org.shoebox.engine.items.actors.AActor;
	import org.shoebox.biskwy.events.ActorEvent;
	import flash.display.StageAlign;
	import flash.display.StageScaleMode;
	import flash.display.NativeWindowType;
	import flash.display.NativeWindowSystemChrome;
	import flash.display.NativeWindowInitOptions;
	import flash.display.NativeWindow;
	import org.shoebox.patterns.singleton.ISingleton;
	import org.shoebox.patterns.commands.AbstractCommand;	import org.shoebox.patterns.commands.ICommand;	import org.shoebox.utils.logger.Logger;	import flash.events.Event;	/**	* org.shoebox.biskwy.commands.actor.CommandEditActor	* @author shoebox	*/	public class CommandEditActor extends AbstractCommand implements ICommand , ISingleton {				protected var _oREF_ACTOR				: AActor;		protected var _oPROPS					: ActorProps;		protected var _oWINDOW					: NativeWindow;				// -------o constructor					/**			* Constructor of the AScript command class			*			* @public			* @return	void			*/			public function CommandEditActor( e : SingletonEnforcer ) : void {				cancelable = false;			}		// -------o public						/**			* Execution of the command			* 			* @public			* @param	e : optional event (Event) 			* @return	void			*/			override public function onExecute( e : Event = null ) : void {				trc('onExecute ::: '+e);								//					var	oOPT:NativeWindowInitOptions = new NativeWindowInitOptions();						oOPT.resizable = oOPT.maximizable = oOPT.minimizable =  false;						oOPT.systemChrome = NativeWindowSystemChrome.STANDARD;						oOPT.type = NativeWindowType.UTILITY;								//					_oWINDOW = new NativeWindow( oOPT );					_oWINDOW.alwaysInFront = true;					_oWINDOW.width = 300;					_oWINDOW.height = 400;					_oWINDOW.stage.scaleMode = StageScaleMode.NO_SCALE;					_oWINDOW.stage.align = StageAlign.TOP_LEFT;					_oWINDOW.addEventListener( Event.CLOSE , _onClose , false , 10 , true );					_oWINDOW.activate();									//					_oWINDOW.stage.stageHeight = 400;					_oWINDOW.stage.stageWidth = 300;									//					_oPROPS = new ActorProps();
					_oPROPS.setSize(300, 400);
					_oPROPS.addEventListener( PropsPanel.PROP_CHANGED , _onChanged , false , 10 , true );
					_oWINDOW.stage.addChild(_oPROPS);
					actorRef = ( e as ActorEvent ).targetActor;									//					_init();					_edit();			}						/**			* When the command is canceled			* 			* @public			* @param	e : optional event (Event)	 			* @return	void			*/			override public function onCancel( e : Event = null ) : void {				if( _oWINDOW )					if( _oWINDOW.active )						_oWINDOW.close();			}						/**			* set actorRef function			* @public			* @param 			* @return			*/			final public function set actorRef( o : AActor ) : void {				_oPROPS.ref = o;				_oREF_ACTOR = o;				_edit();			}					// -------o protected						/**			* 			*			* @param 			* @return			*/			final protected function _onClose( e : Event ) : void {				_oWINDOW.removeEventListener( Event.CLOSE , _onClose , false );				_oWINDOW = null;				cancel( e );			}						/**			* 			*			* @param 			* @return			*/			final protected function _init() : void {			}						/**			* 			*			* @param 			* @return			*/			final protected function _edit() : void {								if( !_oWINDOW )					return;													_oWINDOW.title = 'Actor editor ::: ' + _oREF_ACTOR+' - '+_oREF_ACTOR.name;								var 	oXML : XML = _oREF_ACTOR.propsXML.copy();								var 	i : uint = 0;				var 	l : uint = oXML..	entry.length();				var 	o : XML;				for( i ; i < l ; i++ ){										o = oXML..entry[i];										if( _oREF_ACTOR.hasOwnProperty( o.@prop ))						o.@value = _oREF_ACTOR[o.@prop];								}								l = oXML..sub.length();				i = 0;				for( i ; i < l ; i++ ){					o = oXML..sub[i];										if( _oREF_ACTOR.hasOwnProperty( o.@prop ))						o.@value = _oREF_ACTOR[o.@prop];				}								_oPROPS.dataProvider = oXML;							}						/**			* 			*			* @param 			* @return			*/			final protected function _onChanged( e : Event ) : void {								var o :PropsPanelItem = e.target as PropsPanelItem;				_oREF_ACTOR[ o.propName ] = o.value;				_oREF_ACTOR.redraw();			}					// -------o misc			public static function trc(...args : *) : void {				Logger.log(CommandEditActor, args);			}						/**			* Return the singleton instance of the class			* @public			* @return instance of the class (CommandEditActor)			*/			static public function getInstance() : CommandEditActor {								if( !__instance )					__instance = new CommandEditActor( new SingletonEnforcer() );												return __instance;			}						protected static var __instance			: CommandEditActor = null;	}}internal class SingletonEnforcer{	}