/**  HomeMade by shoe[box]   Redistribution and use in source and binary forms, with or without   modification, are permitted provided that the following conditions are  met:  * Redistributions of source code must retain the above copyright notice,     this list of conditions and the following disclaimer.    * Redistributions in binary form must reproduce the above copyright    notice, this list of conditions and the following disclaimer in the     documentation and/or other materials provided with the distribution.    * Neither the name of shoe[box] nor the names of its     contributors may be used to endorse or promote products derived from     this software without specific prior written permission.  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS  IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,  THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR  PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR   CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,  EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR  PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF  LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING  NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.*/package org.shoebox.biskwy.commands.tools {
	import org.shoebox.biskwy.core.Config;
	import flash.ui.Keyboard;
	import org.shoebox.engine.core.Keys;
	import flash.events.KeyboardEvent;
	import flash.geom.Point;
	import org.shoebox.biskwy.core.variables.PolyContainer;
	import flash.display.Sprite;
	import org.shoebox.biskwy.core.variables.MapContainer;	import org.shoebox.biskwy.items.PolyItem;	import org.shoebox.patterns.commands.ICommand;	import org.shoebox.patterns.singleton.ISingleton;	import org.shoebox.utils.display.STAGEINSTANCE;	import org.shoebox.utils.logger.Logger;	import flash.events.Event;	import flash.events.MouseEvent;	/**	 * org.shoebox.biskwy.commands.tools.ToolPoly	* @author shoebox	*/	public class ToolPoly extends ATool implements ICommand , ISingleton{				protected var _spPOLY				: PolyItem;		protected var _spTMP				: Sprite;		protected var _vSPOTS				: Vector.<PolyAnchor>;				protected static var __instance		: ToolPoly = null;				// -------o constructor					public function ToolPoly( e : SingletonEnforcer ) : void {			}		// -------o public						/**			* getInstance function			* @public			* @param 			* @return			*/			static public function getInstance() : ToolPoly {								if(!__instance)					__instance = new ToolPoly(new SingletonEnforcer());								return __instance;			}						/**			* onExecute function			* @public			* @param 			* @return			*/			final override public function onExecute( e : Event = null ) : void {				MapContainer.mouseChildren = false;				STAGEINSTANCE.addEventListener( MouseEvent.CLICK , _onMouse , true , 10 , true );				STAGEINSTANCE.addEventListener( KeyboardEvent.KEY_DOWN , _onDown , false , 10 , true );			}						/**			* onCancel function			* @public			* @param 			* @return			*/			final override public function onCancel( e : Event = null ) : void {				STAGEINSTANCE.removeEventListener( MouseEvent.CLICK , _onMouse , true );				STAGEINSTANCE.removeEventListener( KeyboardEvent.KEY_DOWN , _onDown , false );				MapContainer.mouseChildren = true;				__instance = null;				_bISRUNNING = false;			}					// -------o protected						/**			* 			*			* @param 			* @return			*/
			final protected function _onMouse(e : MouseEvent) : void {
				trc('onClick :::: ' + Keys.isDown(Keyboard.CONTROL));				
				var pt : Point = PolyContainer.globalToLocal(new Point(e.stageX, e.stageY));				trace(' ::: '+pt);				if( Keys.isDown(Keyboard.CONTROL)) {
					pt.x = Math.round(pt.x / Config.TILESIZE) * Config.TILESIZE;					pt.y = Math.round(pt.y / Config.TILESIZE) * Config.TILESIZE;					trace('round ::: '+pt);				}									//					if( !_vSPOTS )						_vSPOTS = new Vector.<PolyAnchor>();														// 					var 	o : PolyAnchor = new PolyAnchor( pt );						o.x = pt.x;						o.y = pt.y;					_vSPOTS.push( o );
					PolyContainer.addChild( o );							}						/**			* 			*			* @param 			* @return			*/
			final protected function _onDown(e : KeyboardEvent) : void {
								if( !Keys.isDown(Keyboard.SPACE) )					return;
								if( _vSPOTS.length < 2 )					return;								var o : PolyAnchor;
				var iMAXY : int;
				var iMINY : Number = Infinity;				
				for each( o in _vSPOTS ) {
					iMINY = Math.min( o.ptPos.y, iMINY );
					iMAXY = Math.max( o.ptPos.y, iMAXY );				}				iMAXY+=100;
									var 	i : uint = 0;				var 	l : uint = _vSPOTS.length;				var 	o2 : PolyAnchor;								for( i ; i < l ; i++ ){
										o = _vSPOTS[i]; 					if( (i + 1) == l )						break;											o2 = 	_vSPOTS[i + 1];										_spPOLY = new PolyItem();					_spPOLY.content = Vector.<int>( [	o.x , o.y , o.x , iMAXY , o2.x , o2.y 	] );					PolyContainer.addChild( _spPOLY );										_spPOLY = new PolyItem();					_spPOLY.content = Vector.<int>( [	o.x , iMAXY , o2.x , o2.y , o2.x , iMAXY 	] );					PolyContainer.addChild( _spPOLY );									}								for each( o in _vSPOTS )
					PolyContainer.removeChild( o );									_vSPOTS = new Vector.<PolyAnchor>();							}					// -------o misc			public static function trc(arguments : *) : void {				Logger.log(ToolPoly, arguments);			}	}}import flash.geom.Point;
import flash.display.Sprite;
internal class SingletonEnforcer{}	/**	* org.shoebox.biskwy.commands.tools.PolyAnchor	* @author shoebox	*/	internal class PolyAnchor extends Sprite {				public var ptPos			: Point;				// -------o constructor					/**			* Constructor of the ToolPoly class			*			* @public			* @return	void			*/			public function PolyAnchor( pt : Point ) : void {								ptPos = pt;								graphics.lineStyle( .1 , 0 , 1 , true );								graphics.beginFill( 0xFFFFFF );				graphics.drawRect( -5 , -5 , 10 , 10 );				graphics.endFill();								graphics.moveTo( -2 , 0 );				graphics.lineTo( +2 , 0 );				graphics.moveTo( 0 , -2 );				graphics.lineTo( 0 , +2 );							}		// -------o public				// -------o protected		// -------o misc	}