/**  HomeMade by shoe[box]   Redistribution and use in source and binary forms, with or without   modification, are permitted provided that the following conditions are  met:  * Redistributions of source code must retain the above copyright notice,     this list of conditions and the following disclaimer.    * Redistributions in binary form must reproduce the above copyright    notice, this list of conditions and the following disclaimer in the     documentation and/or other materials provided with the distribution.    * Neither the name of shoe[box] nor the names of its     contributors may be used to endorse or promote products derived from     this software without specific prior written permission.  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS  IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,  THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR  PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR   CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,  EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR  PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF  LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING  NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.*/package org.shoebox.biskwy.windows {
	import fl.events.ListEvent;
	import org.shoebox.biskwy.core.variables.SelectedActor;
	import fl.data.DataProvider;
	import fl.controls.List;
	import org.shoebox.engine.items.actors.*;	import flash.display.StageScaleMode;
	import flash.display.StageAlign;
	import org.shoebox.patterns.factory.Factory;
	import flash.display.NativeWindowInitOptions;
	import flash.display.NativeWindow;
	import org.shoebox.utils.logger.Logger;		/**	* org.shoebox.biskwy.windows.ActorsWindow	* @author shoebox	*/	public class ActorsWindow extends NativeWindow {				protected var _vACTORS				 : Vector.<Class> = Vector.<Class>([ 																Trigger,																PlayerStart,																Sound,																LadderBox,																POI															  ] );				protected var _oLIST				: List;				// -------o constructor					/**			* Constructor of the ActorsWindow class			*			* @public			* @return	void			*/			public function ActorsWindow() : void {								super( Factory.build( NativeWindowInitOptions , {														resizable : false , 													maximizable : false , minimizable : false 												} ));								title = 'Actors';								//					stage.align = StageAlign.TOP_LEFT;					stage.scaleMode = StageScaleMode.NO_SCALE;					stage.nativeWindow.visible = false;								//						stage.stageWidth = 200;					stage.stageHeight = 300;							}		// -------o public						/**			* activate function			* @public			* @param 			* @return			*/			final override public function activate() : void {				trc('activate');				super.activate();				_run();			}						/**			* close function			* @public			* @param 			* @return			*/			final override public function close() : void {				trc('close');
				if( _oLIST)					_oLIST.removeEventListener( ListEvent.ITEM_CLICK , _onClick , false ); 									super.close();			}					// -------o protected						/**			* 			*			* @param 			* @return			*/			final protected function _run() : void {								//					SelectedActor = _vACTORS[0];					var oDP : DataProvider = new DataProvider();					var c : Class;
					for each( c in _vACTORS )
						oDP.addItem({label:c, value:c});
							//					_oLIST = Factory.build( List , { 											width : 200 ,											height : 300 ,											dataProvider : oDP,											rowHeight : 30										   } );					_oLIST.setStyle('contentPadding', 5);					_oLIST.addEventListener( ListEvent.ITEM_CLICK , _onClick , false , 10 , true );					stage.addChild( _oLIST );								}						/**			* 			*			* @param 			* @return			*/			final protected function _onClick( e : ListEvent ) : void {				SelectedActor = e.item.value;			}					// -------o misc			public static function trc(...args : *) : void {				Logger.log(ActorsWindow, args);			}	}}