/**  HomeMade by shoe[box]   Redistribution and use in source and binary forms, with or without   modification, are permitted provided that the following conditions are  met:  * Redistributions of source code must retain the above copyright notice,     this list of conditions and the following disclaimer.    * Redistributions in binary form must reproduce the above copyright    notice, this list of conditions and the following disclaimer in the     documentation and/or other materials provided with the distribution.    * Neither the name of shoe[box] nor the names of its     contributors may be used to endorse or promote products derived from     this software without specific prior written permission.  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS  IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,  THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR  PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR   CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,  EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR  PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF  LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING  NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.*/package org.shoebox.engine.items.actors {
	import org.shoebox.engine.core.variables.ActorModes;
	import org.shoebox.engine.datas.ActorsModes;
	import org.shoebox.engine.events.actorsEvents.LadderEvents;
	import org.shoebox.engine.core.variables.Position2D;
	import org.shoebox.engine.core.variables.PlayerSize;
	import org.shoebox.engine.interfaces.IMoveListener;
	import flash.display.JointStyle;
	import flash.display.CapsStyle;
	import flash.geom.Rectangle;
	import flash.geom.Point;
	import flash.display.BlendMode;
	import org.shoebox.engine.interfaces.IActor;
	import org.shoebox.utils.logger.Logger;		/**	* org.shoebox.engine.items.actors.LadderBox	* @author shoebox	*/	public class LadderBox extends AActor implements IActor , IMoveListener {				public static const LADDER			: String = 'LadderMODE';				[NVM_Variable]			public var recWidth				: uint = 100;				[NVM_Variable]			public var recHeight				: uint = 100;				protected var _bTOUCHED			: Boolean = false ;		protected var _ptPOSITION			: Point ;		protected var _oREC				: Rectangle;		protected var _uLINECOL			: uint = 0x66CC33;				// -------o constructor					/**			* Constructor of the LadderBox class			*			* @public			* @return	void			*/			public function LadderBox() : void {				trc('LadderBox');				alpha = .7;				blendMode = BlendMode.LIGHTEN;								propsXML = <root>				      		<entry label = "LadderBox properties" prop='infottl'	type = "title" />				      		<entry label = "Rectangle shape"	prop='infottl'	type = "title" >				      			<sub label = 'width' 		prop='recWidth' 	type = "number" 	value = "100" />				      			<sub label = 'height' 		prop='recHeight' 	type = "number" 	value = "100" />				      		</entry>				      	</root>;								redraw();				doubleClickEnabled = true;			}		// -------o public						/**			* redraw function			* @public			* @param 			* @return			*/			final override public function redraw() : void {				trc('redraw');				graphics.clear();								//					var uSIZE : uint = 5;					graphics.beginFill( _uLINECOL , 1 );					graphics.drawCircle( 0 , 0 , uSIZE * 3);					graphics.endFill();								//						graphics.lineStyle( 3 , 0 , 1 , true , null , CapsStyle.SQUARE );					graphics.moveTo( -uSIZE , -uSIZE);					graphics.lineTo( -uSIZE , +uSIZE);					graphics.lineTo( +uSIZE , +uSIZE);									//					graphics.lineStyle(10, _uLINECOL, 1, true, null, null, JointStyle.MITER);					_oREC = new Rectangle( -recWidth / 2 , -recHeight / 2 , recWidth , recHeight );					graphics.drawRect(_oREC.x, _oREC.y, _oREC.width, _oREC.height);					_ptPOSITION = new Point( x , y );					_oREC.offset(_ptPOSITION.x, _ptPOSITION.y );						}						/**			* onMove function			* @public			* @param 			* @return			*/			final public function onMove() : void {												var 	oREC : Rectangle = PlayerSize.clone();
					oREC.offset(Position2D.x, Position2D.y);
							var 	oREC2 : Rectangle = _oREC.clone();				//	oREC2.offsetPoint( _ptPOSITION );											var b : Boolean = oREC.intersects( oREC2 );								if( _bTOUCHED !== b ){					dispatchEvent( new LadderEvents( b ? LadderEvents.Touched : LadderEvents.unTouched ) );
					_bTOUCHED = b;										if( b )
						ActorModes.addActiveMode( this , LADDER );					else						ActorModes.removeActiveMode( this , LADDER );				}			}					// -------o protected		// -------o misc			public static function trc(...args : *) : void {				Logger.log(LadderBox, args);			}	}}