/**  HomeMade by shoe[box]   Redistribution and use in source and binary forms, with or without   modification, are permitted provided that the following conditions are  met:  * Redistributions of source code must retain the above copyright notice,     this list of conditions and the following disclaimer.    * Redistributions in binary form must reproduce the above copyright    notice, this list of conditions and the following disclaimer in the     documentation and/or other materials provided with the distribution.    * Neither the name of shoe[box] nor the names of its     contributors may be used to endorse or promote products derived from     this software without specific prior written permission.  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS  IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,  THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR  PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR   CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,  EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR  PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF  LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING  NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.*/package org.shoebox.biskwy.core {	
	import flash.data.SQLStatement;
	import org.shoebox.patterns.service.ServiceEvent;
	import org.shoebox.biskwy.services.STilePreloader;
	import org.shoebox.patterns.service.ServiceBatch;
	import org.shoebox.biskwy.data.TileDesc;
	import flash.events.Event;
	import flash.events.SQLEvent;
	import flash.events.SQLUpdateEvent;
	import org.shoebox.collections.HashMap;
	import org.shoebox.utils.logger.Logger;		/**	* org.shoebox.biskwy.core.TilesCacher	* @author shoebox	*/	public class TilesCacher extends HashMap{				[Event(name="COMPLETE", type="flash.events.Event")]				protected var _oBASE			: DatabaseAssets;		protected var _oBATCH			: ServiceBatch;		protected var _oBATCHTILE		: ServiceBatch;				// -------o constructor					/**			* Constructor of the TilesCache class			*			* @public			* @return	void			*/			public function TilesCacher( b : Boolean = true ) : void {				trc('constructor ::: '+b);				_oBATCHTILE = new ServiceBatch();				super( b );			}		// -------o public						/**			* update function			* @public			* @param 			* @return			*/			final public function update() : void {				trc('update');			}						/**			* init function			* @public			* @param 			* @return			*/			final public function init() : void {				trc('init');				_oBASE = DatabaseAssets.getInstance( );				_oBASE.addEventListener( SQLUpdateEvent.UPDATE 	, _onUpdate , false , 10 , true );				_oBASE.addEventListener( SQLUpdateEvent.INSERT 	, _onUpdate , false , 10 , true );				_oBASE.addEventListener( SQLUpdateEvent.DELETE 	, _onUpdate , false , 10 , true );				_oBASE.addEventListener( SQLEvent.RESULT		, _onResults , false , 10 , true );				_oBASE.call('SELECT * FROM TilesDB');			}					// -------o protected						/**			* 			*			* @param 			* @return			*/			final protected function _onDatas ( e : SQLEvent ) : void {				trc('onDatas ::: '+e);							}						/**			* 			*			* @param 			* @return			*/			final protected function _onUpdate( e : SQLUpdateEvent ) : void {				trc('onUpdate ::: '+e.type+' /// '+e.table+' /// '+e.rowID);								switch( e.type ){
										case SQLUpdateEvent.UPDATE:						trc('update');						break;										case SQLUpdateEvent.INSERT:						if( e.table == 'TilesDB' ){														trc('rowID ::: '+e.rowID );							var 	oSTTMT : SQLStatement = new SQLStatement();								oSTTMT.sqlConnection = _oBASE.connection;								oSTTMT.text = 'SELECT * FROM TilesDB WHERE id=:id';								oSTTMT.parameters[':id'] = e.rowID;								oSTTMT.addEventListener( SQLEvent.RESULT , _onUpdateRes , false , 10 , true );								oSTTMT.execute( );													}						break;									}							}						/**			* 			*			* @param 			* @return			*/			final protected function _onUpdateRes( e : SQLEvent ) : void {				trc('_onUpdateRes ::: '+e);				(e.target as SQLStatement).removeEventListener( SQLEvent.RESULT , _onUpdateRes , false );								var o : Object = (e.target as SQLStatement).getResult().data[0];				var p : String;				for( p in o ){					trace(p+' /// '+o[p]);				}								trc('addFileToBactch ::: '+o);								_oBATCHTILE.addService( STilePreloader , { datas : o } );								if( !_oBATCHTILE.isRunning )					_oBATCHTILE.call();									_preCacheDesc( o );							}						/**			* 			*			* @param 			* @return			*/			final protected function _onResults( e : SQLEvent ) : void {				_oBASE.removeEventListener( SQLEvent.RESULT		, _onResults , false );				trace('_oBASE.getResults() ::: '+_oBASE.getResults());				if( _oBASE.getResults() == null ){					dispatchEvent( new Event( Event.COMPLETE ) );					return;				}													var a : Array = _oBASE.getResults().data;				if( a == null ){						dispatchEvent( new Event( Event.COMPLETE ) );					return;				}								var i : uint = 0;				var l : uint = a.length;				var o : Object;								for( i ; i < l ; i++ ){					o = a[i];										_preCacheDesc( o );										if( !_oBATCH )						_oBATCH = new ServiceBatch( );						_oBATCH.addService( STilePreloader , { datas : o } );										}								if( !_oBATCH)					dispatchEvent( new Event( Event.COMPLETE ) );
				else {
					_oBATCH.addEventListener(ServiceEvent.ON_DATAS , _onCacheComplete , false , 10 , true );					_oBATCH.call( );				}							}						/**			* 			*			* @param 			* @return			*/			final protected function _preCacheDesc( o : Object ) : void {								var p : String;				var t : TileDesc = new TileDesc( );				for( p in o ){					if( t.hasOwnProperty(p))						t[p] = o[p];				}									addItem( o.AssetID , t );			}						/**			* 			*			* @param 			* @return			*/			final protected function _onCacheComplete( e : ServiceEvent ) : void {				trc('_onCacheComplete :: '+e);				_oBATCH.removeEventListener(ServiceEvent.ON_DATAS , _onCacheComplete , false );				_oBATCH = null;				dispatchEvent( new Event( Event.COMPLETE ) );			}					// -------o misc			public static function trc(...args : *) : void {				Logger.log(TilesCacher, args);			}	}}